export interface Product {
  name: string;
  slug: string;
  description?: string;
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  image: string;
  color: string;
  products: Product[];
}

export const categories: Category[] = [
  {
    name: "Acais",
    slug: "acais",
    description: "O verdadeiro sabor da Amazonia em cada colherada",
    image: "/images/categories/acais (2).png",
    color: "#4a1942",
    products: [
      { name: "Acai com Iogurte Grego", slug: "acai-iogurte-grego", description: "Cremosidade do iogurte grego com o poder do acai" },
      { name: "Acai com Sorbet de Maracuja", slug: "acai-sorbet-maracuja", description: "Refrescancia tropical com maracuja" },
      { name: "Acai", slug: "acai", description: "O classico acai puro e cremoso" },
      { name: "Acai com Guarana", slug: "acai-guarana", description: "Energia dobrada com guarana" },
      { name: "Acai com Ninho", slug: "acai-ninho", description: "Suavidade do leite ninho com acai" },
      { name: "Acai Natural", slug: "acai-natural", description: "100% natural, sem adicao de acucar" },
      { name: "Acai Natural Pote", slug: "acai-natural-pote", description: "Acai natural no pote para levar" },
      { name: "Acai Leitinho", slug: "acai-leitinho", description: "Cremoso com toque de leite condensado" },
      { name: "Acai Zero", slug: "acai-zero", description: "Todo sabor sem acucar" },
      { name: "Acai Tradicional", slug: "acai-tradicional", description: "Receita tradicional consagrada" },
      { name: "Acai c/ Banana", slug: "acai-banana", description: "Combinacao classica com banana" },
      { name: "Acai c/ Morango", slug: "acai-morango", description: "Frescor do morango com acai" },
      { name: "Acai c/ Pasta de Amendoim", slug: "acai-pasta-amendoim", description: "Proteina e sabor juntos" },
    ],
  },
  {
    name: "Aurus",
    slug: "aurus",
    description: "Linha premium com sabores sofisticados e exclusivos",
    image: "/images/categories/aurus.png",
    color: "#c8a45a",
    products: [
      { name: "Pistache", slug: "aurus-pistache", description: "O nobre sabor do pistache premium" },
      { name: "Aurus Goldko Chocolate", slug: "aurus-goldko-chocolate", description: "Chocolate Goldko zero acucar" },
      { name: "Aurus Goldko Cookies", slug: "aurus-goldko-cookies", description: "Cookies Goldko zero acucar" },
      { name: "Aurus Goldko Pistache", slug: "aurus-goldko-pistache", description: "Pistache Goldko zero acucar" },
      { name: "Sorvete de Cookies", slug: "aurus-sorvete-cookies", description: "Cookies crocantes no sorvete" },
      { name: "Sorvete Leite Trufado", slug: "aurus-leite-trufado", description: "Leite trufado irresistivel" },
      { name: "Panna Cotta", slug: "aurus-panna-cotta", description: "Inspirado no classico italiano" },
      { name: "Sorvete Chocolate com Avela", slug: "aurus-chocolate-avela", description: "Chocolate belga com avelas" },
      { name: "Cookies", slug: "aurus-cookies", description: "Pedacos generosos de cookies" },
      { name: "Doce de Leite", slug: "aurus-doce-leite", description: "Doce de leite mineiro autentico" },
      { name: "Vanilla com Chocolate", slug: "aurus-vanilla-chocolate", description: "Classico duo irresistivel" },
      { name: "Panna Cotta com Avelas", slug: "aurus-panna-cotta-avelas", description: "Sofisticacao com avelas crocantes" },
      { name: "Cafe Moka", slug: "aurus-cafe-moka", description: "Para os amantes de cafe" },
      { name: "Picole Cheesecake com Morango", slug: "aurus-cheesecake-morango", description: "Cheesecake no palito" },
      { name: "Mousse de Limao", slug: "aurus-mousse-limao", description: "Leveza do mousse de limao" },
    ],
  },
  {
    name: "Bombonzinho",
    slug: "bombonzinho",
    description: "Bombons de sorvete cobertos com chocolate premium",
    image: "/images/categories/bombom.png",
    color: "#5c3317",
    products: [
      { name: "Bombom de Sorvete Pistache", slug: "bombom-pistache", description: "Pistache coberto com chocolate" },
      { name: "Bombom de Sorvete Vanilla Cream", slug: "bombom-vanilla-cream", description: "Vanilla cream com cobertura crocante" },
    ],
  },
  {
    name: "Cone",
    slug: "cone",
    description: "Casquinhas crocantes recheadas com sorvete premium",
    image: "/images/categories/cone.png",
    color: "#d4903a",
    products: [
      { name: "Cone Mais Leite", slug: "cone-mais-leite", description: "Casquinha com sorvete de leite" },
      { name: "Cone Pistache", slug: "cone-pistache", description: "Casquinha com sorvete de pistache" },
    ],
  },
  {
    name: "Fit",
    slug: "fit",
    description: "Linha fitness com whey protein para quem cuida da saude",
    image: "/images/categories/fit.png",
    color: "#2d7d46",
    products: [
      { name: "Picole Whey Amendoim", slug: "fit-whey-amendoim", description: "Whey protein com pasta de amendoim" },
      { name: "Picole Whey Cacau", slug: "fit-whey-cacau", description: "Whey protein com cacau" },
    ],
  },
  {
    name: "Frutas",
    slug: "frutas",
    description: "Sabores naturais feitos com frutas selecionadas",
    image: "/images/categories/fruta.png",
    color: "#e67e22",
    products: [
      { name: "Abacaxi", slug: "frutas-abacaxi", description: "Refrescante picole de abacaxi" },
      { name: "Limao", slug: "frutas-limao", description: "Azedinho na medida certa" },
      { name: "Tangerina", slug: "frutas-tangerina", description: "Sabor citrico da tangerina" },
      { name: "Uva", slug: "frutas-uva", description: "Doce e refrescante" },
      { name: "Mais Fruta Amora", slug: "frutas-amora", description: "Intensidade da amora silvestre" },
      { name: "Mais Fruta Morango", slug: "frutas-morango", description: "Morango fresco e natural" },
      { name: "Mais Fruta Manga", slug: "frutas-manga", description: "Manga madura e suculenta" },
      { name: "Picole de Fruta Limao e Uva", slug: "frutas-limao-uva", description: "Duo refrescante limao e uva" },
      { name: "Picole de Fruta Tangerina", slug: "frutas-tangerina-picole", description: "Tangerina pura no palito" },
    ],
  },
  {
    name: "Kids",
    slug: "kids",
    description: "Diversao e sabor para a criancada",
    image: "/images/categories/kids.png",
    color: "#e84393",
    products: [
      { name: "Pegada Freddy", slug: "kids-pegada-freddy", description: "Formato divertido de pegada" },
      { name: "Algodao Doce", slug: "kids-algodao-doce", description: "Sabor de algodao doce magico" },
      { name: "Love Unicornio", slug: "kids-love-unicornio", description: "Colorido e encantador" },
      { name: "Love Moranguinho", slug: "kids-love-moranguinho", description: "Morango com muito carinho" },
      { name: "Solzinho", slug: "kids-solzinho", description: "Formato de sol radiante" },
      { name: "Esse e Meu", slug: "kids-esse-e-meu", description: "Exclusivo para os pequenos" },
      { name: "Sundae Morango", slug: "kids-sundae-morango", description: "Mini sundae de morango" },
      { name: "Magia do Unicornio", slug: "kids-magia-unicornio", description: "Pura magia em cada mordida" },
    ],
  },
  {
    name: "Linha Chocoblito",
    slug: "linha-chocoblito",
    description: "Explosao de chocolate em formato compacto",
    image: "/images/categories/chocoblito.png",
    color: "#3d1c02",
    products: [
      { name: "Chocoblito", slug: "chocoblito-original", description: "O classico Chocoblito" },
      { name: "Rockers", slug: "chocoblito-rockers", description: "Chocoblito versao rocker" },
      { name: "Chocoblito Nuts", slug: "chocoblito-nuts", description: "Com amendoas e castanhas" },
      { name: "Franblito", slug: "chocoblito-franblito", description: "Framboesa com chocolate" },
    ],
  },
  {
    name: "Paletas",
    slug: "paletas",
    description: "Paletas gourmet artesanais com recheio generoso",
    image: "/images/categories/paletas.png",
    color: "#8e3a59",
    products: [
      { name: "Coco Bianco", slug: "paleta-coco-bianco", description: "Coco cremoso coberto de chocolate branco" },
      { name: "Gourmet Leite Trufado", slug: "paleta-leite-trufado", description: "Recheio trufado irresistivel" },
      { name: "Gourmet Morango com Leite Condensado", slug: "paleta-morango-condensado", description: "Morango com leite condensado" },
      { name: "Lisa Pacoca", slug: "paleta-pacoca", description: "Sabor pacoca tipicamente brasileiro" },
      { name: "Special Gran Avela", slug: "paleta-gran-avela", description: "Avela premium importada" },
    ],
  },
  {
    name: "Picolés",
    slug: "picoles",
    description: "Classicos picoles para refrescar seu dia",
    image: "/images/categories/picoles (1).png",
    color: "#e74c3c",
    products: [
      { name: "Acai", slug: "picole-acai", description: "Picole cremoso de acai" },
      { name: "Abacaxi", slug: "picole-abacaxi", description: "Refrescante abacaxi no palito" },
      { name: "Limao", slug: "picole-limao", description: "Limao azedinho e gelado" },
      { name: "Tangerina", slug: "picole-tangerina", description: "Citrico e natural" },
      { name: "Uva", slug: "picole-uva", description: "Doce sabor de uva" },
      { name: "Mais Fruta Amora", slug: "picole-amora", description: "Amora silvestre intensa" },
      { name: "Mais Fruta Morango", slug: "picole-morango", description: "Morango fresco e doce" },
      { name: "Mais Fruta Manga", slug: "picole-manga", description: "Manga tropical suculenta" },
      { name: "Brigadeiro", slug: "picole-brigadeiro", description: "O docinho brasileiro no palito" },
      { name: "Coco", slug: "picole-coco", description: "Coco cremoso e refrescante" },
      { name: "Milho Verde", slug: "picole-milho-verde", description: "Sabor de milho verde de festa" },
      { name: "Chocolate", slug: "picole-chocolate", description: "Chocolate puro e intenso" },
      { name: "Mais Leite", slug: "picole-mais-leite", description: "Extra cremoso com mais leite" },
      { name: "Pegada Freddy", slug: "picole-pegada-freddy", description: "Divertido formato de pegada" },
      { name: "Algodao Doce", slug: "picole-algodao-doce", description: "Algodao doce colorido" },
      { name: "Love Unicornio", slug: "picole-love-unicornio", description: "Magico e colorido" },
    ],
  },
  {
    name: "Potes",
    slug: "potes",
    description: "Sorvetes premium em potes para toda a familia",
    image: "/images/categories/potes.png",
    color: "#2c3e50",
    products: [
      { name: "Acai Natural Pote", slug: "pote-acai-natural", description: "Acai natural puro no pote" },
      { name: "Acai Leitinho", slug: "pote-acai-leitinho", description: "Acai cremoso com leite" },
      { name: "Pistache", slug: "pote-pistache", description: "Nobre pistache premium" },
      { name: "Sorvete de Cookies", slug: "pote-cookies", description: "Repleto de pedacos de cookies" },
      { name: "Sorvete Leite Trufado", slug: "pote-leite-trufado", description: "Leite trufado aveludado" },
      { name: "Panna Cotta", slug: "pote-panna-cotta", description: "Delicadeza italiana" },
      { name: "Sorvete Chocolate com Avela", slug: "pote-chocolate-avela", description: "Chocolate belga com avela" },
      { name: "Strogonoff de Nozes", slug: "pote-strogonoff-nozes", description: "Edicao limitada exclusiva" },
      { name: "Amor em Pedacos", slug: "pote-amor-pedacos", description: "Pedacos de amor em cada colherada" },
      { name: "Cheesecake com Morango", slug: "pote-cheesecake-morango", description: "Cheesecake cremoso com morango" },
      { name: "Bombom Trufado", slug: "pote-bombom-trufado", description: "Bombom trufado cremoso" },
      { name: "Banana com Avelas", slug: "pote-banana-avelas", description: "Banana com avelas crocantes" },
      { name: "Sorvete Chocotri", slug: "pote-chocotri", description: "Triplo chocolate" },
      { name: "Sorvete de Flocos", slug: "pote-flocos", description: "Classico flocos cremoso" },
      { name: "Sorvete Napolitano", slug: "pote-napolitano", description: "Trio classico napolitano" },
      { name: "Sorvete Creme Amarelo", slug: "pote-creme-amarelo", description: "Creme amarelo tradicional" },
    ],
  },
  {
    name: "Sobremesas",
    slug: "sobremesas",
    description: "Sobremesas especiais para momentos unicos",
    image: "/images/categories/sobremesas.png",
    color: "#6c3483",
    products: [
      { name: "Brownie Chocolate Dubai Pistache", slug: "sobremesa-brownie-dubai", description: "Brownie com pistache estilo Dubai" },
      { name: "Brownie Rockers", slug: "sobremesa-brownie-rockers", description: "Brownie com sorvete rocker" },
      { name: "New York Rockers", slug: "sobremesa-ny-rockers", description: "Inspirado na Big Apple" },
      { name: "Taca Banoffee", slug: "sobremesa-banoffee", description: "Classica sobremesa inglesa" },
      { name: "Dubai Roll", slug: "sobremesa-dubai-roll", description: "Rolinho estilo Dubai" },
      { name: "Taca KitKat", slug: "sobremesa-kitkat", description: "Com pedacos de KitKat" },
      { name: "Churros Ice Cream", slug: "sobremesa-churros", description: "Churros com sorvete" },
      { name: "Gran Gateau Cookies", slug: "sobremesa-gran-gateau", description: "Gateau de cookies premium" },
      { name: "Choux Cream", slug: "sobremesa-choux-cream", description: "Massa choux recheada" },
      { name: "Petit Gateau", slug: "sobremesa-petit-gateau", description: "Classico petit gateau quente" },
      { name: "Sopa de Bis", slug: "sobremesa-sopa-bis", description: "Camadas de Bis com sorvete" },
      { name: "Sopa de Chocolate", slug: "sobremesa-sopa-chocolate", description: "Chocolate quente com sorvete" },
      { name: "Profiteroles", slug: "sobremesa-profiteroles", description: "Profiteroles franceses" },
      { name: "MilkShake Leite Trufado", slug: "sobremesa-milkshake-trufado", description: "Milkshake cremoso trufado" },
      { name: "MilkShake Cookies", slug: "sobremesa-milkshake-cookies", description: "Milkshake com cookies" },
      { name: "MilkShake Ferrero", slug: "sobremesa-milkshake-ferrero", description: "Milkshake Ferrero Rocher" },
    ],
  },
  {
    name: "Sorvetes Self Service",
    slug: "sorvetes-self-service",
    description: "Monte seu sorvete do jeito que voce quiser",
    image: "/images/categories/acais (1).png",
    color: "#16a085",
    products: [
      { name: "Acai com Sorbet de Maracuja", slug: "self-acai-maracuja", description: "Acai com refrescancia do maracuja" },
      { name: "Sorbet de Goiaba", slug: "self-sorbet-goiaba", description: "Sorbet leve de goiaba" },
      { name: "Tapioca com Coco", slug: "self-tapioca-coco", description: "Sabor brasileiro autentico" },
      { name: "Tangerina", slug: "self-tangerina", description: "Citrico e refrescante" },
      { name: "Morangos Silvestres", slug: "self-morangos-silvestres", description: "Morango silvestre delicado" },
      { name: "Abacaxi", slug: "self-abacaxi", description: "Frescor tropical" },
      { name: "Manga Uba", slug: "self-manga-uba", description: "Manga uba mineira" },
      { name: "Baunilha com Morango", slug: "self-baunilha-morango", description: "Duo classico" },
      { name: "Chocolate", slug: "self-chocolate", description: "Chocolate intenso" },
      { name: "Cookies", slug: "self-cookies", description: "Pedacos de cookies" },
    ],
  },
  {
    name: "Speciale",
    slug: "speciale",
    description: "Sabores especiais de edicao limitada",
    image: "/images/categories/speciale.png",
    color: "#8e44ad",
    products: [
      { name: "Strogonoff de Nozes", slug: "speciale-strogonoff-nozes", description: "Edicao limitada exclusiva" },
      { name: "Amor em Pedacos", slug: "speciale-amor-pedacos", description: "Sabores que emocionam" },
      { name: "Cheesecake com Morango", slug: "speciale-cheesecake", description: "Cheesecake artesanal" },
      { name: "Bombom Trufado", slug: "speciale-bombom-trufado", description: "Trufa premium" },
    ],
  },
  {
    name: "Zero Acucar",
    slug: "zero-acucar",
    description: "Todo sabor sem nenhum acucar adicionado",
    image: "/images/categories/zeroa.png",
    color: "#27ae60",
    products: [
      { name: "Aurus Goldko Chocolate", slug: "zero-goldko-chocolate", description: "Chocolate premium sem acucar" },
      { name: "Aurus Goldko Cookies", slug: "zero-goldko-cookies", description: "Cookies sem acucar" },
      { name: "Aurus Goldko Pistache", slug: "zero-goldko-pistache", description: "Pistache sem acucar" },
      { name: "Chocolate Zero", slug: "zero-chocolate", description: "Chocolate intenso sem acucar" },
      { name: "Picole Whey Amendoim", slug: "zero-whey-amendoim", description: "Whey sem acucar" },
      { name: "Picole Whey Cacau", slug: "zero-whey-cacau", description: "Whey cacau sem acucar" },
      { name: "Sorvete Baunilha com Morango", slug: "zero-baunilha-morango", description: "Baunilha e morango sem acucar" },
      { name: "Sorvete Chocolate Zero", slug: "zero-sorvete-chocolate", description: "Sorvete chocolate zero" },
      { name: "Acai Zero", slug: "zero-acai", description: "Acai sem acucar adicionado" },
      { name: "Baunilha com Morango Zero", slug: "zero-baunilha-morango-self", description: "Self service sem acucar" },
      { name: "Cookies Zero", slug: "zero-cookies", description: "Cookies sem acucar" },
    ],
  },
  {
    name: "Zero Lactose",
    slug: "zero-lactose",
    description: "Deliciosos sabores sem nenhuma lactose",
    image: "/images/categories/zerolactose.png",
    color: "#2980b9",
    products: [
      { name: "Acai com Sorbet de Maracuja", slug: "zl-acai-maracuja", description: "Acai refrescante sem lactose" },
      { name: "Sorbet de Goiaba", slug: "zl-sorbet-goiaba", description: "Sorbet puro sem lactose" },
      { name: "Acai", slug: "zl-acai", description: "Acai classico sem lactose" },
      { name: "Acai com Guarana", slug: "zl-acai-guarana", description: "Energia sem lactose" },
      { name: "Acai Natural Pote", slug: "zl-acai-natural-pote", description: "Natural sem lactose" },
      { name: "Abacaxi", slug: "zl-abacaxi", description: "Abacaxi refrescante" },
      { name: "Limao", slug: "zl-limao", description: "Limao puro" },
      { name: "Tangerina", slug: "zl-tangerina", description: "Tangerina natural" },
      { name: "Uva", slug: "zl-uva", description: "Uva sem lactose" },
      { name: "Mais Fruta Amora", slug: "zl-amora", description: "Amora silvestre" },
      { name: "Mais Fruta Morango", slug: "zl-morango", description: "Morango natural" },
      { name: "Mais Fruta Manga", slug: "zl-manga", description: "Manga tropical" },
      { name: "Morangos Silvestres", slug: "zl-morangos-silvestres", description: "Morangos do campo" },
      { name: "Manga Uba", slug: "zl-manga-uba", description: "Manga uba mineira" },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
