export interface Product {
  name: string;
  slug: string;
  description?: string;
  image: string;
}

export interface Category {
  name: string;
  slug: string;
  description: string;
  image: string;
  color: string;
  products: Product[];
}

export const categories: Category[] = [
  {
    name: "Acais",
    slug: "acais",
    description: "O verdadeiro sabor da Amazonia em cada colherada",
    image: "/images/categories/acais (2).png",
    color: "#4a1942",
    products: [
      { name: "Acai com Iogurte Grego", slug: "acai-iogurte-grego", description: "Cremosidade do iogurte grego com o poder do acai", image: "/images/products/acai-iorgute-grego (1).png" },
      { name: "Acai com Sorbet de Maracuja", slug: "acai-sorbet-maracuja", description: "Refrescancia tropical com maracuja", image: "/images/products/acai-sorbet-maracuja.png" },
      { name: "Acai", slug: "acai", description: "O classico acai puro e cremoso", image: "/images/products/acai.png" },
      { name: "Acai com Guarana", slug: "acai-guarana", description: "Energia dobrada com guarana", image: "/images/products/acai-guarana.png" },
      { name: "Acai com Ninho", slug: "acai-ninho", description: "Suavidade do leite ninho com acai", image: "/images/products/acai-ninho.png" },
      { name: "Acai Natural", slug: "acai-natural", description: "100% natural, sem adicao de acucar", image: "/images/products/acai-natural.png" },
      { name: "Acai Natural Pote", slug: "acai-natural-pote", description: "Acai natural no pote para levar", image: "/images/products/acai-natural-pote.png" },
      { name: "Acai Leitinho", slug: "acai-leitinho", description: "Cremoso com toque de leite condensado", image: "/images/products/acai-leitinho.png" },
      { name: "Acai Zero", slug: "acai-zero", description: "Todo sabor sem acucar", image: "/images/products/acai-zero.png" },
      { name: "Acai Tradicional", slug: "acai-tradicional", description: "Receita tradicional consagrada", image: "/images/products/acai-tradicional.png" },
      { name: "Acai c/ Banana", slug: "acai-banana", description: "Combinacao classica com banana", image: "/images/products/acai-banana.png" },
      { name: "Acai c/ Morango", slug: "acai-morango", description: "Frescor do morango com acai", image: "/images/products/acai-morango.png" },
      { name: "Acai c/ Pasta de Amendoim", slug: "acai-pasta-amendoim", description: "Proteina e sabor juntos", image: "/images/products/acai-amendoim.png" },
    ],
  },
  {
    name: "Aurus",
    slug: "aurus",
    description: "Linha premium com sabores sofisticados e exclusivos",
    image: "/images/categories/aurus.png",
    color: "#c8a45a",
    products: [
      { name: "Pistache", slug: "aurus-pistache", description: "O nobre sabor do pistache premium", image: "/images/products/pistache-pote.png" },
      { name: "Aurus Goldko Chocolate", slug: "aurus-goldko-chocolate", description: "Chocolate Goldko zero acucar", image: "/images/products/chocolate-zero.png" },
      { name: "Aurus Goldko Cookies", slug: "aurus-goldko-cookies", description: "Cookies Goldko zero acucar", image: "/images/products/cookies-zero.png" },
      { name: "Aurus Goldko Pistache", slug: "aurus-goldko-pistache", description: "Pistache Goldko zero acucar", image: "/images/products/pistache-zero.png" },
      { name: "Sorvete de Cookies", slug: "aurus-sorvete-cookies", description: "Cookies crocantes no sorvete", image: "/images/products/cookies-pote.png" },
      { name: "Sorvete Leite Trufado", slug: "aurus-leite-trufado", description: "Leite trufado irresistivel", image: "/images/products/leite-trufado-pote.png" },
      { name: "Panna Cotta", slug: "aurus-panna-cotta", description: "Inspirado no classico italiano", image: "/images/products/pannacota-pote.png" },
      { name: "Sorvete Chocolate com Avela", slug: "aurus-chocolate-avela", description: "Chocolate belga com avelãs", image: "/images/products/chocolate-avelas-pote.png" },
      { name: "Cookies", slug: "aurus-cookies", description: "Pedacos generosos de cookies", image: "/images/products/cookies-picole.png" },
      { name: "Doce de Leite", slug: "aurus-doce-leite", description: "Doce de leite mineiro autentico", image: "/images/products/doce-leite.png" },
      { name: "Vanilla com Chocolate", slug: "aurus-vanilla-chocolate", description: "Classico duo irresistivel", image: "/images/products/vanilla.png" },
      { name: "Panna Cotta com Avelas", slug: "aurus-panna-cotta-avelas", description: "Sofisticacao com avelas crocantes", image: "/images/products/pannacota.png" },
      { name: "Cafe Moka", slug: "aurus-cafe-moka", description: "Para os amantes de cafe", image: "/images/products/cafe.png" },
      { name: "Picole Cheesecake com Morango", slug: "aurus-cheesecake-morango", description: "Cheesecake no palito", image: "/images/products/cheesecake.png" },
      { name: "Mousse de Limao", slug: "aurus-mousse-limao", description: "Leveza do mousse de limao", image: "/images/products/limao (1).png" },
      { name: "Mousse de Maracujá", slug: "Aurus-mousse-maracuja", description: "Delícia com casquinha de chocolate branco", image: "/images/products/maracuja.png" }
    ],
  },
  {
    name: "Bombonzinho",
    slug: "bombonzinho",
    description: "Bombons de sorvete cobertos com chocolate premium",
    image: "/images/categories/bombom.png",
    color: "#5c3317",
    products: [
      { name: "Bombom de Sorvete Pistache", slug: "bombom-pistache", description: "Pistache coberto com chocolate", image: "/images/products/bombom-pistache.png" },
      { name: "Bombom de Sorvete Vanilla Cream", slug: "bombom-vanilla-cream", description: "Vanilla cream com cobertura crocante", image:"/images/products/bombom-vanilla.png" },
    ],
  },
  {
    name: "Cone",
    slug: "cone",
    description: "Casquinhas crocantes recheadas com sorvete premium",
    image: "/images/categories/cone.png",
    color: "#d4903a",
    products: [
      { name: "Cone Mais Leite", slug: "cone-mais-leite", description: "Casquinha com sorvete de leite", image:"/images/products/cone-leite.png" },
      { name: "Cone Pistache", slug: "cone-pistache", description: "Casquinha com sorvete de pistache", image:"/images/products/cone-pistache.png" },
    ],
  },
  {
    name: "Fit",
    slug: "fit",
    description: "Linha fitness com whey protein para quem cuida da saude",
    image: "/images/categories/fit.png",
    color: "#2d7d46",
    products: [
      { name: "Picole Whey Amendoim", slug: "fit-whey-amendoim", description: "Whey protein com pasta de amendoim", image: "/images/products/fit-amendoim.png" },
      { name: "Picole Whey Cacau", slug: "fit-whey-cacau", description: "Whey protein com cacau", image: "/images/products/fit-cacau.png" },
    ],
  },
  {
    name: "Frutas",
    slug: "frutas",
    description: "Sabores naturais feitos com frutas selecionadas",
    image: "/images/categories/fruta.png",
    color: "#e67e22",
    products: [
      { name: "Abacaxi", slug: "frutas-abacaxi", description: "Refrescante picole de abacaxi", image: "/images/products/fruta-abacaxi.png" },
      { name: "Limao", slug: "frutas-limao", description: "Azedinho na medida certa", image: "/images/products/fruta-limao.png" },
      { name: "Tangerina", slug: "frutas-tangerina", description: "Sabor citrico da tangerina", image: "/images/products/fruta-tangerina.png" },
      { name: "Uva", slug: "frutas-uva", description: "Doce e refrescante", image: "/images/products/fruta-uva.png" },
      { name: "Mais Fruta Amora", slug: "frutas-amora", description: "Intensidade da amora silvestre", image: "/images/products/fruta-amora.png" },
      { name: "Mais Fruta Morango", slug: "frutas-morango", description: "Morango fresco e natural", image: "/images/products/fruta-morango.png" },
      { name: "Mais Fruta Manga", slug: "frutas-manga", description: "Manga madura e suculenta", image: "/images/products/fruta-manga.png" },
    ]
  },
  {
    name: "Kids",
    slug: "kids",
    description: "Diversao e sabor para a criancada",
    image: "/images/categories/kids.png",
    color: "#e84393",
    products: [
      { name: "Pegada Freddy", slug: "kids-pegada-freddy", description: "Formato divertido de pegada", image: "/images/products/pegada-freddy.png" },
      { name: "Algodao Doce", slug: "kids-algodao-doce", description: "Sabor de algodao doce magico", image: "/images/products/algodao-doce.png" },
      { name: "Love Unicornio", slug: "kids-love-unicornio", description: "Colorido e encantador", image: "/images/products/love-unicornio.png" },
      { name: "Love Moranguinho", slug: "kids-love-moranguinho", description: "Morango com muito carinho", image: "/images/products/love-moranguinho.png" },
     
      { name: "Sundae Morango", slug: "kids-sundae-morango", description: "Mini sundae de morango", image: "/images/products/sundae-morango.png" },
      { name: "Magia do Unicornio", slug: "kids-magia-unicornio", description: "Pura magia em cada mordida", image: "/images/products/magia-unicornio.png" },
    ],
  },
  {
    name: "Linha Chocoblito",
    slug: "linha-chocoblito",
    description: "Explosao de chocolate em formato compacto",
    image: "/images/categories/chocoblito.png",
    color: "#3d1c02",
    products: [
      { name: "Chocoblito", slug: "chocoblito-original", description: "O classico Chocoblito", image: "/images/products/chocoblito.png" },
      { name: "Rockers", slug: "chocoblito-rockers", description: "Chocoblito versao rocker", image: "/images/products/chocoblito-rockers (1).png" },
      { name: "Chocoblito Nuts", slug: "chocoblito-nuts", description: "Com amendoas e castanhas", image: "/images/products/chocoblito-nuts (1).png" },
      { name: "Franblito", slug: "chocoblito-franblito", description: "Framboesa com chocolate", image: "/images/products/franblito (1).png" },
    ],
  },
  {
    name: "Paletas",
    slug: "paletas",
    description: "Paletas gourmet artesanais com recheio generoso",
    image: "/images/categories/paletas.png",
    color: "#8e3a59",
    products: [
      { name: "Coco Bianco", slug: "paleta-coco-bianco", description: "Coco cremoso coberto de chocolate branco" },
      { name: "Gourmet Leite Trufado", slug: "paleta-leite-trufado", description: "Recheio trufado irresistivel" },
      { name: "Gourmet Morango com Leite Condensado", slug: "paleta-morango-condensado", description: "Morango com leite condensado" },
      { name: "Lisa Pacoca", slug: "paleta-pacoca", description: "Sabor pacoca tipicamente brasileiro" },
      { name: "Special Gran Avela", slug: "paleta-gran-avela", description: "Avela premium importada" },
    ],
  },
  {
    name: "Picolés",
    slug: "picoles",
    description: "Classicos picoles para refrescar seu dia",
    image: "/images/categories/picoles (1).png",
    color: "#e74c3c",
    products: [
      { name: "Acai", slug: "picole-acai", description: "Picole cremoso de acai" },
      { name: "Abacaxi", slug: "picole-abacaxi", description: "Refrescante abacaxi no palito" },
      { name: "Limao", slug: "picole-limao", description: "Limao azedinho e gelado" },
      { name: "Tangerina", slug: "picole-tangerina", description: "Citrico e natural" },
      { name: "Uva", slug: "picole-uva", description: "Doce sabor de uva" },
      { name: "Mais Fruta Amora", slug: "picole-amora", description: "Amora silvestre intensa" },
      { name: "Mais Fruta Morango", slug: "picole-morango", description: "Morango fresco e doce" },
      { name: "Mais Fruta Manga", slug: "picole-manga", description: "Manga tropical suculenta" },
      { name: "Brigadeiro", slug: "picole-brigadeiro", description: "O docinho brasileiro no palito" },
      { name: "Coco", slug: "picole-coco", description: "Coco cremoso e refrescante" },
      { name: "Milho Verde", slug: "picole-milho-verde", description: "Sabor de milho verde de festa" },
      { name: "Chocolate", slug: "picole-chocolate", description: "Chocolate puro e intenso" },
      { name: "Mais Leite", slug: "picole-mais-leite", description: "Extra cremoso com mais leite" },
      { name: "Pegada Freddy", slug: "picole-pegada-freddy", description: "Divertido formato de pegada" },
      { name: "Algodao Doce", slug: "picole-algodao-doce", description: "Algodao doce colorido" },
      { name: "Love Unicornio", slug: "picole-love-unicornio", description: "Magico e colorido" },
    ],
  },
  {
    name: "Potes",
    slug: "potes",
    description: "Sorvetes premium em potes para toda a familia",
    image: "/images/categories/potes.png",
    color: "#2c3e50",
    products: [
      { name: "Acai Natural Pote", slug: "pote-acai-natural", description: "Acai natural puro no pote" },
      { name: "Acai Leitinho", slug: "pote-acai-leitinho", description: "Acai cremoso com leite" },
      { name: "Pistache", slug: "pote-pistache", description: "Nobre pistache premium" },
      { name: "Sorvete de Cookies", slug: "pote-cookies", description: "Repleto de pedacos de cookies" },
      { name: "Sorvete Leite Trufado", slug: "pote-leite-trufado", description: "Leite trufado aveludado" },
      { name: "Panna Cotta", slug: "pote-panna-cotta", description: "Delicadeza italiana" },
      { name: "Sorvete Chocolate com Avela", slug: "pote-chocolate-avela", description: "Chocolate belga com avela" },
      { name: "Strogonoff de Nozes", slug: "pote-strogonoff-nozes", description: "Edicao limitada exclusiva" },
      { name: "Amor em Pedacos", slug: "pote-amor-pedacos", description: "Pedacos de amor em cada colherada" },
      { name: "Cheesecake com Morango", slug: "pote-cheesecake-morango", description: "Cheesecake cremoso com morango" },
      { name: "Bombom Trufado", slug: "pote-bombom-trufado", description: "Bombom trufado cremoso" },
      { name: "Banana com Avelas", slug: "pote-banana-avelas", description: "Banana com avelas crocantes" },
      { name: "Sorvete Chocotri", slug: "pote-chocotri", description: "Triplo chocolate" },
      { name: "Sorvete de Flocos", slug: "pote-flocos", description: "Classico flocos cremoso" },
      { name: "Sorvete Napolitano", slug: "pote-napolitano", description: "Trio classico napolitano" },
      { name: "Sorvete Creme Amarelo", slug: "pote-creme-amarelo", description: "Creme amarelo tradicional" },
    ],
  },
  {
    name: "Sobremesas",
    slug: "sobremesas",
    description: "Sobremesas especiais para momentos unicos",
    image: "/images/categories/sobremesas.png",
    color: "#6c3483",
    products: [
      { name: "Brownie Chocolate Dubai Pistache", slug: "sobremesa-brownie-dubai", description: "Brownie com pistache estilo Dubai" },
      { name: "Brownie Rockers", slug: "sobremesa-brownie-rockers", description: "Brownie com sorvete rocker" },
      { name: "New York Rockers", slug: "sobremesa-ny-rockers", description: "Inspirado na Big Apple" },
      { name: "Taca Banoffee", slug: "sobremesa-banoffee", description: "Classica sobremesa inglesa" },
      { name: "Dubai Roll", slug: "sobremesa-dubai-roll", description: "Rolinho estilo Dubai" },
      { name: "Taca KitKat", slug: "sobremesa-kitkat", description: "Com pedacos de KitKat" },
      { name: "Churros Ice Cream", slug: "sobremesa-churros", description: "Churros com sorvete" },
      { name: "Gran Gateau Cookies", slug: "sobremesa-gran-gateau", description: "Gateau de cookies premium" },
      { name: "Choux Cream", slug: "sobremesa-choux-cream", description: "Massa choux recheada" },
      { name: "Petit Gateau", slug: "sobremesa-petit-gateau", description: "Classico petit gateau quente" },
      { name: "Sopa de Bis", slug: "sobremesa-sopa-bis", description: "Camadas de Bis com sorvete" },
      { name: "Sopa de Chocolate", slug: "sobremesa-sopa-chocolate", description: "Chocolate quente com sorvete" },
      { name: "Profiteroles", slug: "sobremesa-profiteroles", description: "Profiteroles franceses" },
      { name: "MilkShake Leite Trufado", slug: "sobremesa-milkshake-trufado", description: "Milkshake cremoso trufado" },
      { name: "MilkShake Cookies", slug: "sobremesa-milkshake-cookies", description: "Milkshake com cookies" },
      { name: "MilkShake Ferrero", slug: "sobremesa-milkshake-ferrero", description: "Milkshake Ferrero Rocher" },
    ],
  },
  {
    name: "Sorvetes Self Service",
    slug: "sorvetes-self-service",
    description: "Monte seu sorvete do jeito que voce quiser",
    image: "/images/categories/acais (1).png",
    color: "#16a085",
    products: [
      { name: "Acai com Sorbet de Maracuja", slug: "self-acai-maracuja", description: "Acai com refrescancia do maracuja", image: "/images/products/acai-sorbet-maracuja.png" },
      { name: "Acai com Guarana", slug: "self-acai-guarana", description: "Energia do acai com guarana", image: "/images/products/acai-tradicional.png" },
      { name: "Acai com Ninho", slug: "self-acai-ninho", description: "Cremoso acai com leite ninho", image: "/images/products/acai-ninho (1).png" },
      
      { name: "Açai c/ Morango", slug: "self-acai-morango", description: "Acai com frescor do morango", image: "/images/products/acai-morango.png" },
      { name: "Acai c/ Banana", slug: "self-acai-banana", description: "Acai com doçura da banana", image: "/images/products/acai-banana.png" },
      { name: "Acai c/ Pasta de Amendoim", slug: "self-acai-pasta-amendoim", description: "Acai com sabor intenso de amendoim", image: "/images/products/acai-amendoim.png" },
      { name: "Acai Zero", slug: "self-acai-zero", description: "Todo sabor do acai sem acucar", image: "/images/products/acai-zero.png" },
      { name: "Sorbet de Goiaba", slug: "self-sorbet-goiaba", description: "Sorbet leve de goiaba", image: "/images/products/sorbet-goiaba.png" },
      { name: "Cookies zero Acucar", slug: "self-cookies-zero", description: "Cookies sem acucar", image: "/images/products/cookies-zero-bola.png" },
      { name: "Chocolate Zero", slug: "self-chocolate-zero", description: "Chocolate intenso sem acucar", image: "/images/products/chocolate-zero-bola.png" },
      { name: "Baunilha com Morango", slug: "self-baunilha-morango", description: "Clássico sabor de baunilha com morango", image: "/images/products/baunilha-zero-bola.png" },
      {name: "Uva", slug: "self-uva", description: "Doce e refrescante", image: "/images/products/uva-bola.png" },
      { name: "Tapioca com Coco", slug: "self-tapioca-coco", description: "Sabor brasileiro autentico", image: "/images/products/tapioca-coco.png" },
      { name: "Tangerina", slug: "self-tangerina", description: "Citrico e refrescante", image: "/images/products/tangerina-bola.png" },
      { name: "Morangos Silvestres", slug: "self-morangos-silvestres", description: "Morango silvestre delicado", image: "/images/products/morangos-silvestres-bola.png" },
      { name: "Abacaxi", slug: "self-abacaxi", description: "Frescor tropical", image: "/images/products/abacaxi-bola.png" },
      { name: "Manga Uba", slug: "self-manga-uba", description: "Manga uba mineira", image: "/images/products/manga-bola.png" },
      { name: "Limao", slug: "self-limao", description: "Limao azedinho e refrescante", image: "/images/products/limao-bola.png" },
      { name: "Morango", slug: "self-morango", description: "Morango fresco e doce", image: "/images/products/morango-bola.png" },
      { name: "Mousse de Maracujá", slug: "self-mousse-maracuja", description: "Leve mousse de maracujá", image: "/images/products/maracuja-bola.png" },
      { name: "Paçoca", slug: "self-pacoca", description: "Sabor de paçoca tradicional", image: "/images/products/pacoca-bola.png" },
      { name: "Panna Cotta com Avelas", slug: "self-panna-cotta-avelas", description: "Sofisticacao com avelas crocantes", image: "/images/products/pannacota-bola.png" },
      { name: "Sorvete de Flocos", slug: "self-flocos", description: "Clássico sorvete de flocos", image: "/images/products/flocos-bola.png" },
      { name: "Passas ao Rum", slug: "self-passas-rum", description: "Passas embebidas em rum", image: "/images/products/passas-rum.png" },
      { name: "Pavê de Chocolate", slug: "self-pave-chocolate", description: "Camadas de chocolate e creme", image: "/images/products/pave-chocolate.png" },
      { name: "Pistache", slug: "self-pistache", description: "O nobre sabor do pistache premium", image: "/images/products/pistache-bola.png" },
      { name: "Leite Trufado", slug: "self-leite-trufado", description: "Leite trufado aveludado", image: "/images/products/leite-trufado-bola.png" },
      { name: "Torta Alemã", slug: "self-torta-alema", description: "Sabor da torta alemã clássica", image: "/images/products/torta-alema.png" },
      { name: "Ovomaltine", slug: "self-ovomaltine", description: "Sabor de ovomaltine crocante", image: "/images/products/ovomaltine.png" },
      { name: "Milho Verde", slug: "self-milho-verde", description: "Sabor de milho verde de festa", image: "/images/products/milho-verde.png" },
      { name: "Menta com Chocolate", slug: "self-menta-chocolate", description: "Refrescancia da menta com chocolate", image: "/images/products/menta-chocolate.png" },
      { name: "Queijo com Goiabada cascão", slug: "self-queijo-goiabada", description: "Sabor brasileiro clássico", image: "/images/products/queijo-goiabada.png" },
      { name: "Magia do Unicornio", slug: "self-magia-unicornio", description: "Sabor mágico e colorido", image: "/images/products/magia-unicornio-bola.png" },
      { name: "Rockers", slug: "self-rockers", description: "Sorvete com pedaços de chocolate crocante", image: "/images/products/rockes.png" },
      { name: "Chocolate", slug: "self-chocolate", description: "Chocolate intenso", image: "/images/products/chocolate.png" },
      { name: "Inteligência Artificial", slug: "self-inteligencia-artificial", description: "Sabor futurista e inovador", image: "/images/products/ia.png" },
      { name: "Gran Avelã", slug: "self-gran-avela", description: "Avelã premium importada", image: "/images/products/gran-avela.png" },
      { name: "Cookies n'Cream", slug: "self-cookies", description: "Pedacos de cookies", image: "/images/products/cookies-zero-bola.png" },
    ],
  },
  {
    name: "Speciale",
    slug: "speciale",
    description: "Sabores especiais de edicao limitada",
    image: "/images/categories/speciale.png",
    color: "#8e44ad",
    products: [
      { name: "Strogonoff de Nozes", slug: "speciale-strogonoff-nozes", description: "Edicao limitada exclusiva", image: "/images/products/strogonoff-nozes.png" },
      { name: "Amor em Pedacos", slug: "speciale-amor-pedacos", description: "Sabores que emocionam", image: "/images/products/amor-pedacos.png" },
      { name: "Cheesecake com Morango", slug: "speciale-cheesecake", description: "Cheesecake artesanal", image: "/images/products/cheesecake-speciale.png" },
      { name: "Bombom Trufado", slug: "speciale-bombom-trufado", description: "Trufa premium", image: "/images/products/bombom-trufado.png" },
    ],
  },
  {
    name: "Zero Acucar",
    slug: "zero-acucar",
    description: "Todo sabor sem nenhum acucar adicionado",
    image: "/images/categories/zeroa.png",
    color: "#27ae60",
    products: [
      { name: "Aurus Goldko Chocolate", slug: "zero-goldko-chocolate", description: "Chocolate premium sem acucar", image: "/images/products/chocolate-zero.png" },
      { name: "Aurus Goldko Cookies", slug: "zero-goldko-cookies", description: "Cookies sem acucar",  image: "/images/products/cookies-zero.png" },
      { name: "Aurus Goldko Pistache", slug: "zero-goldko-pistache", description: "Pistache sem acucar", image: "/images/products/pistache-zero.png" },
      { name: "Chocolate Zero", slug: "zero-chocolate", description: "Chocolate intenso sem acucar", image: "/images/products/chocolate-zero2.png" },
      { name: "Picole Whey Amendoim", slug: "zero-whey-amendoim", description: "Whey sem acucar", image: "/images/products/fit-amendoim.png" },
      { name: "Picole Whey Cacau", slug: "zero-whey-cacau", description: "Whey cacau sem acucar", image: "/images/products/fit-cacau.png" },
      { name: "Sorvete Baunilha com Morango", slug: "zero-baunilha-morango", description: "Baunilha e morango sem acucar", image: "/images/products/baunilha-zero.png" },
      { name: "Sorvete Chocolate Zero", slug: "zero-sorvete-chocolate", description: "Sorvete chocolate zero", image: "/images/products/chocolate-pote.png" },
      { name: "Acai Zero", slug: "zero-acai", description: "Acai sem acucar adicionado", image: "/images/products/acai-zero.png" },
      { name: "Baunilha com Morango Zero", slug: "zero-baunilha-morango-self", description: "Self service sem acucar", image: "/images/products/baunilha-zero-bola.png" },
      { name: "Cookies Zero", slug: "zero-cookies", description: "Cookies sem acucar", image: "/images/products/cookies-zero-bola.png" },
      { name: "Chocolate Zero", slug: "zero-chocolate-self", description: "Self service chocolate zero", image: "/images/products/chocolate-zero-bola.png" },
    ],
  },
  {
    name: "Zero Lactose",
    slug: "zero-lactose",
    description: "Deliciosos sabores sem nenhuma lactose",
    image: "/images/categories/zerolactose.png",
    color: "#2980b9",
    products: [
      { name: "Acai com Sorbet de Maracuja", slug: "zl-acai-maracuja", description: "Acai refrescante sem lactose", image: "/images/products/acai-sorbet-maracuja.png" },
      { name: "Sorbet de Goiaba", slug: "zl-sorbet-goiaba", description: "Sorbet puro sem lactose", image: "/images/products/sorbet-goiaba.png" },
      { name: "Acai", slug: "zl-acai", description: "Acai classico sem lactose", image: "/images/products/acai.png" },
      { name: "Acai com Guarana", slug: "zl-acai-guarana", description: "Energia sem lactose", image: "/images/products/acai-guarana.png" },
      { name: "Acai Natural Pote", slug: "zl-acai-natural-pote", description: "Natural sem lactose", image: "/images/products/acai-natural-pote.png" },
      { name: "Abacaxi", slug: "zl-abacaxi", description: "Abacaxi refrescante", image: "/images/products/fruta-abacaxi.png" },
      { name: "Limao", slug: "zl-limao", description: "Limao puro e azedinho", image: "/images/products/fruta-limao.png" },
      { name: "Tangerina", slug: "zl-tangerina", description: "Tangerina natural", image: "/images/products/fruta-tangerina.png" },
      { name: "Uva", slug: "zl-uva", description: "Uva sem lactose", image: "/images/products/fruta-uva.png" },
      { name: "Mais Fruta Amora", slug: "zl-amora", description: "Amora silvestre", image: "/images/products/fruta-amora.png" },
      { name: "Mais Fruta Morango", slug: "zl-morango", description: "Morango natural", image: "/images/products/fruta-morango.png" },
      { name: "Mais Fruta Manga", slug: "zl-manga", description: "Manga tropical", image: "/images/products/fruta-manga.png" },
      { name: "Manga Uba", slug: "zl-manga-uba", description: "Manga uba mineira", image: "/images/products/fruta-manga.png" },
      { name: "Morangos Silvestres", slug: "zl-morangos-silvestres", description: "Morangos do campo", image: "/images/products/morangos-silvestres.png" },
      
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}
